apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  namespace: public-service
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: jenkins.xxx.net
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
   
