apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: elasticsearch-exporter
    release: es-exporter
  name: es-exporter-elasticsearch-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9108
    protocol: TCP
    targetPort: 9108
  selector:
    k8s-app: elasticsearch-exporter
    release: es-exporter
  sessionAffinity: None
  type: ClusterIP
