kind: Endpoints
apiVersion: v1
metadata:
  name: external-es
  namespace: logging
  labels:
    k8s-app: elasticsearch-logging
subsets:
  - addresses:
      - ip: 10.120.114.193
      - ip: 10.120.114.194
      - ip: 10.120.114.195
    ports:
      - port: 9200
        name: es
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: external-es
  namespace: logging
  labels:
    k8s-app: elasticsearch-logging
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
    name: es