apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
kubernetesVersion: v1.12.3
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
api:
  advertiseAddress: 192.168.20.20
  controlPlaneEndpoint: k8s-master-lb:16443
controllerManagerExtraArgs:
  node-monitor-grace-period: 10s
  pod-eviction-timeout: 10s

apiServerCertSANs:
- 192.168.20.20
- 192.168.20.21
- 192.168.20.22
- k8s-master-lb
- k8s-master01
- k8s-master02
- k8s-master03
- 192.168.20.10
etcd:
  local:
    extraArgs:
      listen-client-urls: "https://127.0.0.1:2379,https://192.168.20.20:2379"
      advertise-client-urls: "https://192.168.20.20:2379"
      listen-peer-urls: "https://192.168.20.20:2380"
      initial-advertise-peer-urls: "https://192.168.20.20:2380"
      initial-cluster: "k8s-master01=https://192.168.20.20:2380"
    serverCertSANs:
      - k8s-master01
      - 192.168.20.20
    peerCertSANs:
      - k8s-master01
      - 192.168.20.20
networking:
  podSubnet: "172.168.0.0/16"
#kubeProxy:
#  config:
#    featureGates:
#      SupportIPVSProxyMode: true
#    mode: ipvs
