apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab
  namespace: public-service
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: gitlab.xxx.net
    http:
      paths:
      - backend:
          serviceName: gitlab
          servicePort: 80
   
