apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-workspace
  labels:
    app: cicd
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: jenkins-workspace