{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "harbor.fullname" . }}-ingress"
  labels:
{{ include "harbor.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.hosts.core }}
    - {{ .Values.ingress.hosts.notary }}
    {{- if .Values.ingress.tls.secretName }}
    secretName: {{ .Values.ingress.tls.secretName }}
    {{- else }}
    secretName: "{{ template "harbor.fullname" . }}-ingress"
    {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.hosts.core }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "harbor.fullname" . }}-ui
          servicePort: 80
  {{- if .Values.notary.enabled }}
  - host: {{ .Values.ingress.hosts.notary }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "harbor.notaryServiceName" . }}
          servicePort: 4443
  {{- end }}
{{- end }}