persistence:
  enabled: &persistence_enabled true
# Ther external URL for Harbor core service. It is used to
# 1) populate the docker/helm commands showed on portal
# 2) populate the token service URL returned to docker/notary client
# 
# Format: protocol://domain[:port]
# Usually, if ingress is enabled, the domain should be the value of
# ingress.hosts.core .
# If Harbor is deployed behind the proxy, set it as the URL of proxy
externalURL: https://harbor.xxx.net

ingress:
  enabled: true
  hosts:
    core: harbor.xxx.net
    notary: notary.xxx.net
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  tls:
    enabled: true
    # Fill the secretName if you want to use the certificate of 
    # yourself when Harbor serves with HTTPS. A certificate will 
    # be generated automatically by the chart if leave it empty
    secretName: ""

harborAdminPassword: Harbor12345
# The secret key used for encryption. Must be a string of 16 chars.
secretKey: not-a-secure-key

imagePullPolicy: &image_pull_policy IfNotPresent

adminserver:
  image:
    repository: goharbor/harbor-adminserver
    tag: v1.6.0
    pullPolicy: *image_pull_policy
  # resources:
  #  requests:
  #    memory: 256Mi
  #    cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}

jobservice:
  image:
    repository: goharbor/harbor-jobservice
    tag: v1.6.0
    pullPolicy: *image_pull_policy
  maxWorkers: 50
# resources:
#   requests:
#     memory: 256Mi
#     cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}

ui:
  image:
    repository: goharbor/harbor-ui
    tag: v1.6.0
    pullPolicy: *image_pull_policy
# resources:
#  requests:
#    memory: 256Mi
#    cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}

# TODO: change the style to be same with redis
database:
  # if external database is used, set "type" to "external"
  # and fill the connection informations in "external" section
  type: internal
  internal:
    image:
      repository: goharbor/harbor-db
      tag: v1.6.0
      pullPolicy: *image_pull_policy
    # the superuser password of database
    password: "changeit"
    volumes:
      data:
        storageClass: "gluster-heketi"
        accessMode: ReadWriteOnce
        size: 1Gi
    # resources:
    #  requests:
    #    memory: 256Mi
    #    cpu: 100m
    nodeSelector: {}
    tolerations: []
    affinity: {}
  external:
    host: "192.168.0.1"
    port: "5432"
    username: "user"
    password: "password"
    coreDatabase: "registry"
    clairDatabase: "clair"
    notaryServerDatabase: "notary_server"
    notarySignerDatabase: "notary_signer"
    sslmode: "disable"

registry:
  image:
    repository: goharbor/registry-photon
    tag: v2.6.2-v1.6.0
    pullPolicy: *image_pull_policy
  logLevel: info
  storage:
    # specify the type of storage: "filesystem", "azure", "gcs", "s3", "swift", 
    # "oss" and fill the information needed in the corresponding section
    type: filesystem
    filesystem:
      rootdirectory: /var/lib/registry
      #maxthreads: 100
    azure:
      accountname: accountname
      accountkey: base64encodedaccountkey
      container: containername
      #realm: core.windows.net
    gcs:
      bucket: bucketname
      # TODO: support the keyfile of gcs
      #keyfile: /path/to/keyfile
      #rootdirectory: /gcs/object/name/prefix
      #chunksize: 5242880
    s3:
      region: us-west-1
      bucket: bucketname
      #accesskey: awsaccesskey
      #secretkey: awssecretkey
      #regionendpoint: http://myobjects.local
      #encrypt: false
      #keyid: mykeyid
      #secure: true
      #v4auth: true
      #chunksize: 5242880
      #rootdirectory: /s3/object/name/prefix
      #storageclass: STANDARD
    swift:
      authurl: https://storage.myprovider.com/v3/auth
      username: username
      password: password
      container: containername
      #region: fr
      #tenant: tenantname
      #tenantid: tenantid
      #domain: domainname
      #domainid: domainid
      #trustid: trustid
      #insecureskipverify: false
      #chunksize: 5M
      #prefix:
      #secretkey: secretkey
      #accesskey: accesskey
      #authversion: 3
      #endpointtype: public
      #tempurlcontainerkey: false
      #tempurlmethods:
    oss:
      accesskeyid: accesskeyid
      accesskeysecret: accesskeysecret
      region: regionname
      bucket: bucketname
      #endpoint: endpoint
      #internal: false
      #encrypt: false
      #secure: true
      #chunksize: 10M
      #rootdirectory: rootdirectory
  ## Persist data to a persistent volume
  volumes:
    data:
      # existingClaim: ""
      storageClass: "gluster-heketi-2"
      accessMode: ReadWriteOnce
      size: 30Gi
  # resources:
  #  requests:
  #    memory: 256Mi
  #    cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}

chartmuseum:
  enabled: true
  image:
    repository: goharbor/chartmuseum-photon
    tag: v0.7.1-v1.6.0
    pullPolicy: *image_pull_policy
  volumes:
    data:
      # existingClaim: ""
      storageClass: "gluster-heketi"
      accessMode: ReadWriteOnce
      size: 5Gi
  # resources:
  #  requests:
  #    memory: 256Mi
  #    cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}

clair:
  enabled: true
  image:
    repository: goharbor/clair-photon
    tag: v2.0.5-v1.6.0
    pullPolicy: *image_pull_policy
  # The interval of clair updaters, the unit is hour, 
  # set to 0 to disable the updaters
  updatersInterval: 12
  # resources:
  #  requests:
  #    memory: 256Mi
  #    cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}

redis:
  # if external Redis is used, set "external.enabled" to "true"
  # and fill the connection informations in "external" section.
  # or the internal Redis will be used
  usePassword: false
  password: "changeit"
  cluster:
    enabled: false
  master:
    port: 6379
    persistence:
      enabled: *persistence_enabled
      storageClass: "gluster-heketi"
      accessMode: ReadWriteOnce
      size: 1Gi
  persistence:
    # existingClaim:
    storageClass: "gluster-heketi"
  external:
    enabled: false
    host: "192.168.0.2"
    port: "6379"
    databaseIndex: "0"
    usePassword: false
    password: "changeit"

notary:
  enabled: true
  server:
    image:
      repository: goharbor/notary-server-photon
      tag: v0.5.1-v1.6.0
      pullPolicy: *image_pull_policy
  signer:
    image:
      repository: goharbor/notary-signer-photon
      tag: v0.5.1-v1.6.0
      pullPolicy: *image_pull_policy
  nodeSelector: {}
  tolerations: []
  affinity: {}
