{{- $cert := genSelfSignedCert "harbor" nil nil 365 }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.fullname" . }}-ui"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  secretKey: {{ .Values.secretKey | b64enc | quote }}
  secret: {{ randAlphaNum 16 | b64enc | quote }}
  tokenServiceRootCertBundle: {{ $cert.Cert | b64enc | quote }}
  tokenServicePrivateKey: {{ $cert.Key | b64enc | quote }}
  